#!/usr/bin/env python3
"""Build the apex sitemap-index for radoskop.pl.

Google Search Console expects radoskop.pl/sitemap.xml to be a <sitemapindex>
referencing each per-city sitemap. Per-city sitemaps are generated by
generate_sitemap.py (one per `radoskop/cities/{slug}/docs/sitemap.xml`),
served at `https://{slug}.radoskop.pl/sitemap.xml`.

This script writes the index file at `radoskop/docs/sitemap.xml` which
gets shipped to `s3://radoskop-public/_main/sitemap.xml` by
deploy_main_s3 → served at `https://radoskop.pl/sitemap.xml`.

It also writes a small `radoskop/docs/sitemap-main.xml` listing the apex
page itself (the directory of cities), so the index is well-formed.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path
from xml.sax.saxutils import escape


def discover_cities(workspace: Path) -> list[tuple[str, dict]]:
    """List (slug, config) for every city in monorepo, fallback siblings."""
    out: list[tuple[str, dict]] = []
    mono = workspace / "radoskop" / "cities"
    if mono.is_dir():
        for d in sorted(mono.iterdir()):
            cfg = d / "config.json"
            if d.is_dir() and cfg.exists():
                with cfg.open(encoding="utf-8") as f:
                    out.append((d.name, json.load(f)))
        return out
    for d in sorted(workspace.iterdir()):
        if d.is_dir() and d.name.startswith("radoskop-") and d.name != "radoskop-premium":
            slug = d.name[len("radoskop-"):]
            cfg = d / "config.json"
            if cfg.exists():
                with cfg.open(encoding="utf-8") as f:
                    out.append((slug, json.load(f)))
    return out


def write_sitemap_index(out_path: Path, cities: list[tuple[str, dict]], today: str) -> None:
    parts = ['<?xml version="1.0" encoding="UTF-8"?>']
    parts.append('<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">')
    # Apex page itself (directory)
    parts.append("  <sitemap>")
    parts.append("    <loc>https://radoskop.pl/sitemap-main.xml</loc>")
    parts.append(f"    <lastmod>{today}</lastmod>")
    parts.append("  </sitemap>")
    # Per-city sitemaps
    for slug, config in cities:
        site_url = (config.get("site_url") or f"https://{slug}.radoskop.pl").rstrip("/")
        parts.append("  <sitemap>")
        parts.append(f"    <loc>{escape(site_url)}/sitemap.xml</loc>")
        parts.append(f"    <lastmod>{today}</lastmod>")
        parts.append("  </sitemap>")
    parts.append("</sitemapindex>")
    out_path.write_text("\n".join(parts) + "\n", encoding="utf-8")


def write_apex_sitemap(out_path: Path, today: str) -> None:
    """Small urlset for the apex pages: home + the cities directory anchor."""
    parts = ['<?xml version="1.0" encoding="UTF-8"?>']
    parts.append('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">')
    for loc, prio, freq in [
        ("https://radoskop.pl/", "1.0", "daily"),
        ("https://radoskop.pl/#cities", "0.8", "daily"),
        ("https://radoskop.pl/#councilors", "0.7", "weekly"),
        ("https://radoskop.pl/#votes", "0.6", "weekly"),
        ("https://radoskop.pl/#interpelacje", "0.6", "weekly"),
    ]:
        parts.append("  <url>")
        parts.append(f"    <loc>{loc}</loc>")
        parts.append(f"    <lastmod>{today}</lastmod>")
        parts.append(f"    <changefreq>{freq}</changefreq>")
        parts.append(f"    <priority>{prio}</priority>")
        parts.append("  </url>")
    parts.append("</urlset>")
    out_path.write_text("\n".join(parts) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Build apex sitemap.xml index for radoskop.pl")
    parser.add_argument("--workspace", default=None)
    parser.add_argument("--output-dir", default=None)
    args = parser.parse_args()

    script_dir = Path(__file__).resolve().parent
    workspace = (
        Path(args.workspace).resolve()
        if args.workspace
        else script_dir.parent.parent
    )
    out_dir = (
        Path(args.output_dir).resolve()
        if args.output_dir
        else workspace / "radoskop" / "docs"
    )
    out_dir.mkdir(parents=True, exist_ok=True)

    today = datetime.utcnow().strftime("%Y-%m-%d")
    cities = discover_cities(workspace)
    print(f"workspace: {workspace}", file=sys.stderr)
    print(f"discovered: {len(cities)} cities", file=sys.stderr)

    write_sitemap_index(out_dir / "sitemap.xml", cities, today)
    write_apex_sitemap(out_dir / "sitemap-main.xml", today)

    print(f"wrote {out_dir / 'sitemap.xml'} (index, {len(cities) + 1} sitemap refs)", file=sys.stderr)
    print(f"wrote {out_dir / 'sitemap-main.xml'} (apex urlset)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
