#!/usr/bin/env python3
"""Build the apex sitemap-index for radoskop.pl AND radoskop.eu.

Google Search Console (Domain property) discovers content via the apex
`sitemap.xml`, which must be a <sitemapindex> referencing each per-city
sitemap. Per-city sitemaps are generated by generate_seo_pages.py
(`radoskop/cities/{slug}/docs/sitemap.xml`), served at
`https://{slug}.radoskop.{pl,eu}/sitemap.xml`.

Dwie domeny, dwie usługi GSC (sc-domain:radoskop.pl, sc-domain:radoskop.eu):

  --domain pl  (default):
      Index dla radoskop.pl. Listuje WSZYSTKIE niezdezaktywowane miasta
      (PL + zagraniczne .eu — cross-host jest OK w usłudze Domain i nie
      szkodzi pokryciu). Pisany do `radoskop/docs/sitemap.xml`, shipowany
      na s3://radoskop-public/_main/ → https://radoskop.pl/sitemap.xml.

  --domain eu:
      Index dla radoskop.eu. Listuje TYLKO niezdezaktywowane miasta
      zagraniczne (site_url zawiera radoskop.eu). Bez tego usługa
      radoskop.eu widziała w sitemapie wyłącznie 2 URL-e apexu, więc
      Google prawie nie odkrywał ~28k podstron miast .eu. Pisany do
      `radoskop-premium/docs_eu/sitemap.xml`, shipowany na
      s3://radoskop-public/_main_intl/ → https://radoskop.eu/sitemap.xml.

Plus `urllist.xml` generowany w tym samym katalogu — płaski urlset bez
< sitemapindex> i odwołań do subdomen. Dla domen gdzie GSC przez
Cloudflare nie potrafi przetworzyć sitemap index, zgłosić w GSC osobno
jako `urllist.xml`.

W obu trybach miasta z `disabled: true` w config.json są POMIJANE — ich
subdomeny zwracają 404, a wskazywanie ich w sitemapie truje raport
pokrycia (np. rostock.radoskop.eu).
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path
from xml.sax.saxutils import escape
import xml.etree.ElementTree as ET


# Apex pages per domena (urlset w sitemap-main.xml). /auth/ celowo pominięte.
APEX_PAGES = {
    "pl": [
        ("https://radoskop.pl/", "1.0", "daily"),
        ("https://radoskop.pl/#cities", "0.8", "daily"),
        ("https://radoskop.pl/#councilors", "0.7", "weekly"),
        ("https://radoskop.pl/#votes", "0.6", "weekly"),
        ("https://radoskop.pl/#interpelacje", "0.6", "weekly"),
        # NB: /business/ NIE wchodzi do sitemap radoskop.pl. Strona Business
        # jest hostowana kanonicznie pod https://radoskop.eu/business/, a
        # radoskop.pl/business/ oraz radoskop.pl/premium/ tylko 301 redirect
        # przez worker. Sitemap dla .eu listuje /business/ osobno (niżej).
    ],
    "eu": [
        ("https://radoskop.eu/", "1.0", "daily"),
        ("https://radoskop.eu/pro/", "0.9", "monthly"),
        ("https://radoskop.eu/business/", "0.9", "monthly"),
        ("https://radoskop.eu/pricing/", "0.8", "monthly"),
        ("https://radoskop.eu/reports/", "0.7", "weekly"),
    ],
}

APEX_BASE = {"pl": "https://radoskop.pl", "eu": "https://radoskop.eu"}


def discover_districts(workspace: Path) -> list[tuple[str, dict]]:
    """(slug, config) rad powiatów: tylko scrape_status=="active".

    Scaffoldy pending (przed onboardingiem) nie mają strony na S3, więc
    wpis w sitemapie robiłby 404 i truł raport pokrycia GSC, dokładnie
    jak kiedyś disabled miasta."""
    out: list[tuple[str, dict]] = []
    base = workspace / "radoskop" / "districts"
    if not base.is_dir():
        return out
    for d in sorted(base.iterdir()):
        cfg_path = d / "config.json"
        if not (d.is_dir() and cfg_path.exists()):
            continue
        with cfg_path.open(encoding="utf-8") as f:
            cfg = json.load(f)
        if cfg.get("scrape_status", "active") != "active":
            continue
        out.append((d.name, cfg))
    return out


def discover_cities(workspace: Path) -> list[tuple[str, dict]]:
    """List (slug, config) for every city in monorepo, fallback siblings."""
    out: list[tuple[str, dict]] = []
    mono = workspace / "radoskop" / "cities"
    if mono.is_dir():
        for d in sorted(mono.iterdir()):
            cfg = d / "config.json"
            if d.is_dir() and cfg.exists():
                with cfg.open(encoding="utf-8") as f:
                    out.append((d.name, json.load(f)))
        return out
    for d in sorted(workspace.iterdir()):
        if d.is_dir() and d.name.startswith("radoskop-") and d.name != "radoskop-premium":
            slug = d.name[len("radoskop-"):]
            cfg = d / "config.json"
            if cfg.exists():
                with cfg.open(encoding="utf-8") as f:
                    out.append((slug, json.load(f)))
    return out


def is_eu(config: dict) -> bool:
    return "radoskop.eu" in (config.get("site_url") or "")


def select_cities(
    cities: list[tuple[str, dict]], domain: str
) -> list[tuple[str, dict]]:
    """Filtruj wg domeny.

    W obu trybach miasta z `disabled: true` są POMIJANE — ich subdomeny
    zwracają 404, a wskazywanie ich w sitemapie truje raport pokrycia GSC
    (w usłudze radoskop.pl widać je jako "1 error / 18 URLs").

    domain == 'eu': dodatkowo TYLKO miasta zagraniczne (.eu); miasta PL są
        pomijane, bo należą do usługi radoskop.pl.
    domain == 'pl': wszystkie niezdezaktywowane miasta (PL + .eu) — cross-host
        jest OK w usłudze Domain.
    """
    selected: list[tuple[str, dict]] = []
    for slug, config in cities:
        if config.get("disabled"):
            continue
        if domain == "eu" and not is_eu(config):
            continue
        selected.append((slug, config))
    return selected
def write_sitemap_index(
    out_path: Path, cities: list[tuple[str, dict]], domain: str, today: str
) -> None:
    apex = APEX_BASE[domain]
    parts = ['<?xml version="1.0" encoding="UTF-8"?>']
    parts.append('<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">')
    # Apex page itself (directory)
    parts.append("  <sitemap>")
    parts.append(f"    <loc>{apex}/sitemap-main.xml</loc>")
    parts.append(f"    <lastmod>{today}</lastmod>")
    parts.append("  </sitemap>")
    # Krajowy rejestr spółek — strony /company/{krs}/ żyją tylko na radoskop.pl
    # (build_national_spolki.py → docs/companies-sitemap.xml).
    if domain == "pl":
        parts.append("  <sitemap>")
        parts.append(f"    <loc>{apex}/companies-sitemap.xml</loc>")
        parts.append(f"    <lastmod>{today}</lastmod>")
        parts.append("  </sitemap>")
    # Per-city sitemaps
    for slug, config in cities:
        fallback = f"https://{slug}.radoskop.{'eu' if domain == 'eu' else 'pl'}"
        site_url = (config.get("site_url") or fallback).rstrip("/")
        parts.append("  <sitemap>")
        parts.append(f"    <loc>{escape(site_url)}/sitemap.xml</loc>")
        parts.append(f"    <lastmod>{today}</lastmod>")
        parts.append("  </sitemap>")
    parts.append("</sitemapindex>")
    out_path.write_text("\n".join(parts) + "\n", encoding="utf-8")


def write_apex_sitemap(out_path: Path, domain: str, today: str) -> None:
    """Small urlset for the apex pages of the given domain."""
    parts = ['<?xml version="1.0" encoding="UTF-8"?>']
    parts.append('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">')
    for loc, prio, freq in APEX_PAGES[domain]:
        parts.append("  <url>")
        parts.append(f"    <loc>{loc}</loc>")
        parts.append(f"    <lastmod>{today}</lastmod>")
        parts.append(f"    <changefreq>{freq}</changefreq>")
        parts.append(f"    <priority>{prio}</priority>")
        parts.append("  </url>")
    parts.append("</urlset>")
    out_path.write_text("\n".join(parts) + "\n", encoding="utf-8")


_SITEMAP_NS = "http://www.sitemaps.org/schemas/sitemap/0.9"


def _city_docs_dir(workspace: Path, slug: str) -> Path | None:
    """Znajdź katalog docs/ dla danego sluga."""
    for base in ("cities", "districts"):
        d = workspace / "radoskop" / base / slug / "docs"
        if d.is_dir():
            return d
    # Legacy: radoskop-{slug}/docs/
    d = workspace / f"radoskop-{slug}" / "docs"
    if d.is_dir():
        return d
    return None


def _parse_city_sitemap(docs_dir: Path) -> list[dict]:
    """Wczytaj urlset z per-city sitemap.xml.

    Zwraca listę {loc, lastmod?, changefreq?, priority?}.
    """
    path = docs_dir / "sitemap.xml"
    if not path.is_file():
        return []
    try:
        tree = ET.parse(path)
    except Exception:
        return []
    root = tree.getroot()
    urls: list[dict] = []
    for u in root.findall(f"{{{_SITEMAP_NS}}}url"):
        loc_el = u.find(f"{{{_SITEMAP_NS}}}loc")
        if loc_el is None or not loc_el.text:
            continue
        entry: dict = {"loc": loc_el.text}
        for tag in ("lastmod", "changefreq", "priority"):
            el = u.find(f"{{{_SITEMAP_NS}}}{tag}")
            if el is not None and el.text:
                entry[tag] = el.text
        urls.append(entry)
    return urls


def write_flat_urllist(
    out_path: Path,
    cities: list[tuple[str, dict]],
    domain: str,
    today: str,
    workspace: Path | None,
) -> int:
    """Generuj płaski urllist.xml — jeden urlset z WSZYSTKIMI URL-ami.

    Google Search Console (Domain property) na radoskop.eu nie potrafi
    przetworzyć <sitemapindex> z odwołaniami do subdomen przez Cloudflare.
    Ten plik omija ten problem: zawiera bezpośrednio wszystkie URL-e bez
    referencji do subdomen. Zgłoszony jako osobna sitemap w GSC.

    Zwraca liczbę URL-i.
    """
    all_urls: list[dict] = []

    # Apex pages (np. /, /pro/, /business/)
    for loc, prio, freq in APEX_PAGES[domain]:
        all_urls.append({
            "loc": loc, "changefreq": freq, "priority": prio, "lastmod": today,
        })

    # companies-sitemap.xml (tylko .pl)
    if domain == "pl" and workspace is not None:
        spolki_sm = workspace / "radoskop" / "docs" / "companies-sitemap.xml"
        if spolki_sm.is_file():
            try:
                tree = ET.parse(spolki_sm)
                root = tree.getroot()
                for u in root.findall(f"{{{_SITEMAP_NS}}}url"):
                    loc_el = u.find(f"{{{_SITEMAP_NS}}}loc")
                    if loc_el is not None and loc_el.text:
                        all_urls.append({"loc": loc_el.text})
            except Exception:
                print("  WARNING: failed to parse companies-sitemap.xml", file=sys.stderr)

    # Per-city URLs — wczytaj z lokalnych sitemap.xml
    for slug, config in cities:
        docs_dir = _city_docs_dir(workspace, slug) if workspace else None
        if docs_dir is None:
            print(f"  WARNING: no docs dir for {slug}, skipping flat urllist", file=sys.stderr)
            continue
        city_urls = _parse_city_sitemap(docs_dir)
        if not city_urls:
            print(f"  WARNING: no sitemap.xml in {docs_dir}, skipping", file=sys.stderr)
            continue
        # Filtruj tylko URL-e należące do tej domeny
        site_url = (config.get("site_url") or f"https://{slug}.radoskop.{'eu' if domain == 'eu' else 'pl'}").rstrip("/")
        city_urls = [u for u in city_urls if u["loc"].startswith(site_url)]
        all_urls.extend(city_urls)

    # Dedup by loc
    seen: set[str] = set()
    deduped: list[dict] = []
    for u in all_urls:
        if u["loc"] not in seen:
            seen.add(u["loc"])
            deduped.append(u)

    # Generuj XML z paginacją (Google limit: 50 000 URLi na plik)
    MAX_URLS = 50000
    parts: list[list[dict]] = []
    batch: list[dict] = []
    for e in deduped:
        batch.append(e)
        if len(batch) >= MAX_URLS:
            parts.append(batch)
            batch = []
    if batch:
        parts.append(batch)

    base = out_path.with_stem(out_path.stem.replace("urllist", "")) if out_path.stem != "urllist" else out_path.parent
    stem = out_path.stem  # "urllist"

    if len(parts) == 1:
        # Pojedynczy plik, bez paginacji
        _write_urlset(out_path, parts[0])
        n = len(parts[0])
    else:
        # Sitemap index + urllist1.xml, urllist2.xml, …
        index_parts = []
        for i, batch in enumerate(parts, 1):
            part_path = out_path.with_name(f"{stem}{i}.xml")
            _write_urlset(part_path, batch)
            index_parts.append({
                "loc": f"https://radoskop.eu/{part_path.name}",
                "lastmod": today,
            })
        _write_sitemapindex(out_path, index_parts)
        n = len(deduped)

    return n

def _write_urlset(path: Path, urls: list[dict]) -> None:
    parts = ['<?xml version="1.0" encoding="UTF-8"?>']
    parts.append('<urlset xmlns="https://www.sitemaps.org/schemas/sitemap/0.9">')
    for e in urls:
        parts.append("  <url>")
        parts.append(f'    <loc>{escape(e["loc"])}</loc>')
        if "lastmod" in e:
            parts.append(f'    <lastmod>{e["lastmod"]}</lastmod>')
        if "changefreq" in e:
            parts.append(f'    <changefreq>{e["changefreq"]}</changefreq>')
        if "priority" in e:
            parts.append(f'    <priority>{e["priority"]}</priority>')
        parts.append("  </url>")
    parts.append("</urlset>")
    parts.append("")
    path.write_text("\n".join(parts), encoding="utf-8")

def _write_sitemapindex(path: Path, refs: list[dict]) -> None:
    parts = ['<?xml version="1.0" encoding="UTF-8"?>']
    parts.append('<sitemapindex xmlns="https://www.sitemaps.org/schemas/sitemap/0.9">')
    for r in refs:
        parts.append("  <sitemap>")
        parts.append(f'    <loc>{escape(r["loc"])}</loc>')
        if "lastmod" in r:
            parts.append(f'    <lastmod>{r["lastmod"]}</lastmod>')
        parts.append("  </sitemap>")
    parts.append("</sitemapindex>")
    parts.append("")
    path.write_text("\n".join(parts), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build apex sitemap.xml index for radoskop.pl / radoskop.eu"
    )
    parser.add_argument("--workspace", default=None)
    parser.add_argument("--output-dir", default=None)
    parser.add_argument(
        "--domain", choices=("pl", "eu"), default="pl",
        help="Domena apexu: pl (wszystkie miasta) lub eu (tylko zagraniczne).",
    )
    args = parser.parse_args()

    script_dir = Path(__file__).resolve().parent
    workspace = (
        Path(args.workspace).resolve()
        if args.workspace
        else script_dir.parent.parent
    )
    out_dir = (
        Path(args.output_dir).resolve()
        if args.output_dir
        else workspace / "radoskop" / "docs"
    )
    out_dir.mkdir(parents=True, exist_ok=True)

    today = datetime.utcnow().strftime("%Y-%m-%d")
    # Miasta + aktywne rady powiatów przez ten sam select: powiaty mają
    # site_url na radoskop.pl, więc wchodzą do indeksu przy domain=pl,
    # a przy domain=eu is_eu()==False je pomija, tak jak miasta PL.
    all_cities = discover_cities(workspace) + discover_districts(workspace)
    cities = select_cities(all_cities, args.domain)
    skipped = len(all_cities) - len(cities)
    print(f"workspace: {workspace}", file=sys.stderr)
    print(
        f"domain={args.domain}: {len(cities)} jednostek w indeksie "
        f"(pominięto {skipped} disabled/pending/innej domeny)",
        file=sys.stderr,
    )

    write_sitemap_index(out_dir / "sitemap.xml", cities, args.domain, today)
    write_apex_sitemap(out_dir / "sitemap-main.xml", args.domain, today)

    # Płaski urllist.xml — dla domen, gdzie <sitemapindex> z subdomenami
    # nie działa w GSC przez Cloudflare. Jeden urlset, wszystkie URL-e.
    urllist_path = out_dir / "urllist.xml"
    n_urls = write_flat_urllist(urllist_path, cities, args.domain, today, workspace)
    print(f"wrote {urllist_path} (flat urlset, {n_urls} URLs)", file=sys.stderr)

    print(f"wrote {out_dir / 'sitemap.xml'} (index, {len(cities) + 1} sitemap refs)", file=sys.stderr)
    print(f"wrote {out_dir / 'sitemap-main.xml'} (apex urlset)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
