#!/usr/bin/env python3
"""Katalog stringów UI dla landingu (/) i listy radnych (/councillors/).

Klucze są ANGIELSKIE i semantyczne. Źródłem treści jest polski ('pl'),
pozostałe języki to tłumaczenia. Helper catalog(locale) zwraca słownik
key -> tekst z łańcuchem fallbacku: locale -> 'en' -> 'pl'. Dzięki temu
miasto w dowolnym języku nigdy nie zobaczy pustego/zepsutego napisu —
brakujące tłumaczenie spada na angielski.

Stringi parametryczne używają {name}/{votes}/{n}/{bip}/{label}/{total}
i są formatowane w SPA (renderLandingHTML: _t/_tf) oraz w build_seo_content
(generate_site.py) przez str.replace na kluczach {param}.

UWAGA: tłumaczenia da/sk/hu/uk/lt/lv/et dla krótkich etykiet są maszynowe
i warte natywnej weryfikacji. Dłuższe zdania w tych językach świadomie
spadają na EN (patrz brak kluczy *_desc / *_sub poza pl/en/de/cs).
"""
from __future__ import annotations

# Kolejność = priorytet wyświetlania; 'pl' źródło, 'en' uniwersalny fallback.
LOCALES = ["pl", "en", "de", "cs", "nl", "sk", "fr", "da", "hu", "uk", "lt", "lv", "et"]

# key -> {locale: text}. Brak locale => fallback locale->en->pl.
STRINGS: dict[str, dict[str, str]] = {
    # ── Topbar / shared ────────────────────────────────────────────────
    "nav_reports": {"pl": "Raporty", "en": "Reports", "de": "Berichte", "cs": "Reporty",
                    "nl": "Rapporten", "sk": "Reporty", "fr": "Rapports", "da": "Rapporter",
                    "hu": "Jelentések", "uk": "Звіти", "lt": "Ataskaitos", "lv": "Pārskati", "et": "Aruanded"},
    "nav_business": {"pl": "Pro", "en": "Pro"},
    "theme_toggle": {"pl": "Motyw", "en": "Theme", "de": "Thema", "cs": "Motiv", "nl": "Thema",
                     "sk": "Motív", "fr": "Thème", "da": "Tema", "hu": "Téma", "uk": "Тема",
                     "lt": "Tema", "lv": "Motīvs", "et": "Teema"},
    "aria_nav": {"pl": "Główna nawigacja", "en": "Main navigation"},
    "aria_theme": {"pl": "Przełącz motyw", "en": "Toggle theme"},

    # ── Hero ───────────────────────────────────────────────────────────
    # {name} = dopełniacz nazwy (Wrocławia / mazowieckiego). Dla sejmików
    # eyebrow nadpisuje config (rada_name), więc ten klucz dotyczy miast.
    "hero_eyebrow": {"pl": "Rada Miasta {name}", "en": "{name} City Council",
                     "de": "Stadtrat {name}", "cs": "Městská rada {name}",
                     "nl": "Gemeenteraad {name}", "sk": "Mestská rada {name}",
                     "fr": "Conseil municipal de {name}", "da": "Byråd {name}",
                     "hu": "{name} városi tanács", "uk": "Міська рада {name}",
                     "lt": "{name} miesto taryba", "lv": "{name} pilsētas dome", "et": "{name} linnavolikogu"},
    # Wariant dla assembly (sejmik PL / Landtag DE). Nakładany przez
    # catalog(..., assembly=True) na klucz bazowy. {name} = dopełniacz
    # ("Pomorskiego" / "Mecklenburg-Vorpommerns").
    "hero_eyebrow_assembly": {"pl": "Sejmik Województwa {name}", "en": "{name} Regional Assembly",
                              "de": "Landtag {name}"},
    "term_word": {"pl": "kadencja", "en": "term", "de": "Wahlperiode", "cs": "volební období",
                  "nl": "termijn", "sk": "volebné obdobie", "fr": "mandature", "da": "valgperiode",
                  "hu": "ciklus", "uk": "каденція", "lt": "kadencija", "lv": "sasaukums", "et": "koosseis"},
    # [[...]] => wyróżniony fragment (<span class="hl">), zachowuje szyk per język.
    "hero_title": {"pl": "Tak działa [[rada miasta]].", "en": "How the [[city council]] works.",
                   "de": "So arbeitet der [[Stadtrat]].", "cs": "Jak funguje [[městská rada]].",
                   "nl": "Zo werkt de [[gemeenteraad]].", "sk": "Ako funguje [[mestská rada]].",
                   "fr": "Comment fonctionne le [[conseil municipal]].", "da": "Sådan arbejder [[byrådet]].",
                   "hu": "Így működik a [[városi tanács]].", "uk": "Як працює [[міська рада]].",
                   "lt": "Kaip veikia [[miesto taryba]].", "lv": "Kā strādā [[pilsētas dome]].",
                   "et": "Kuidas töötab [[linnavolikogu]]."},
    "hero_title_assembly": {"pl": "Tak działa [[sejmik województwa]].", "en": "How the [[regional assembly]] works.",
                            "de": "So arbeitet der [[Landtag]]."},
    "cta_check_votes": {"pl": "Sprawdź, jak głosują radni", "en": "See how councillors vote",
                        "de": "Sehen, wie Ratsmitglieder abstimmen", "cs": "Jak hlasují zastupitelé",
                        "nl": "Zie hoe raadsleden stemmen", "sk": "Ako hlasujú poslanci",
                        "fr": "Voir comment votent les élus", "da": "Se hvordan rådsmedlemmer stemmer",
                        "hu": "Hogyan szavaznak a képviselők", "uk": "Як голосують депутати",
                        "lt": "Kaip balsuoja tarybos nariai", "lv": "Kā balso deputāti", "et": "Kuidas volikogu liikmed hääletavad"},
    "cta_all_votes": {"pl": "Wszystkie głosowania", "en": "All votes", "de": "Alle Abstimmungen",
                      "cs": "Všechna hlasování", "nl": "Alle stemmingen", "sk": "Všetky hlasovania",
                      "fr": "Tous les votes", "da": "Alle afstemninger", "hu": "Összes szavazás",
                      "uk": "Усі голосування", "lt": "Visi balsavimai", "lv": "Visi balsojumi", "et": "Kõik hääletused"},
    "insight_full": {"pl": "W tej kadencji radni {name} oddali już <strong>{votes} głosów</strong>. Spornych było <strong>{contested}</strong>.",
                     "en": "This term, {name} councillors have cast <strong>{votes} votes</strong>. <strong>{contested}</strong> were contested.",
                     "de": "In dieser Wahlperiode haben die Ratsmitglieder von {name} bereits <strong>{votes} Stimmen</strong> abgegeben. <strong>{contested}</strong> waren umstritten.",
                     "cs": "V tomto volebním období zastupitelé {name} odevzdali už <strong>{votes} hlasů</strong>. Sporných bylo <strong>{contested}</strong>."},
    # Wariant assembly bez {name} — dopełniacz przekazywany przez renderer jest
    # capitalizowany ("Pomorskiego") i nie pasuje do "radni województwa ...".
    "insight_full_assembly": {"pl": "W tej kadencji radni sejmiku oddali już <strong>{votes} głosów</strong>. Spornych było <strong>{contested}</strong>.",
                              "en": "This term, the assembly has cast <strong>{votes} votes</strong>. <strong>{contested}</strong> were contested.",
                              "de": "In dieser Wahlperiode hat der Landtag bereits <strong>{votes} Stimmen</strong> abgegeben. <strong>{contested}</strong> waren umstritten."},
    "insight_light": {"pl": "Rada {name} liczy <strong>{n}</strong> radnych. Sprawdź ich pełną listę i kluby.",
                      "en": "The {name} council has <strong>{n}</strong> members. See the full list and clubs.",
                      "de": "Der Rat von {name} hat <strong>{n}</strong> Mitglieder. Sehen Sie die vollständige Liste und Fraktionen.",
                      "cs": "Rada {name} má <strong>{n}</strong> zastupitelů. Prohlédněte si celý seznam a kluby."},

    # ── Sekcja: liczby ─────────────────────────────────────────────────
    "sec_numbers_h2": {"pl": "Rada w liczbach", "en": "The council in numbers", "de": "Der Rat in Zahlen",
                       "cs": "Rada v číslech", "nl": "De raad in cijfers", "sk": "Rada v číslach",
                       "fr": "Le conseil en chiffres", "da": "Rådet i tal", "hu": "A tanács számokban",
                       "uk": "Рада в цифрах", "lt": "Taryba skaičiais", "lv": "Dome skaitļos", "et": "Volikogu arvudes"},
    "sec_numbers_sub": {"pl": "Aktualny obraz kadencji. Dane odświeżane dwa razy dziennie.",
                        "en": "A current snapshot of the term. Data refreshed twice a day.",
                        "de": "Aktuelles Bild der Wahlperiode. Daten zweimal täglich aktualisiert.",
                        "cs": "Aktuální obraz volebního období. Data se aktualizují dvakrát denně."},
    "stat_votes_label": {"pl": "głosowań imiennych w kadencji", "en": "recorded votes this term",
                         "de": "namentliche Abstimmungen", "cs": "jmenovitých hlasování",
                         "nl": "hoofdelijke stemmingen", "sk": "menovitých hlasovaní", "fr": "votes nominaux",
                         "da": "navnlige afstemninger", "hu": "névszerinti szavazás", "uk": "поіменних голосувань",
                         "lt": "vardinių balsavimų", "lv": "vārdiskie balsojumi", "et": "nimelist hääletust"},
    "stat_councilors_label": {"pl": "radnych pod obserwacją", "en": "councillors monitored",
                              "de": "beobachtete Ratsmitglieder", "cs": "sledovaných zastupitelů",
                              "nl": "gevolgde raadsleden", "sk": "sledovaných poslancov", "fr": "élus suivis",
                              "da": "overvågede rådsmedlemmer", "hu": "figyelt képviselő", "uk": "депутатів під наглядом",
                              "lt": "stebimų narių", "lv": "uzraudzīto deputātu", "et": "jälgitavat liiget"},
    "stat_contested_label": {"pl": "głosowań spornych (różnica &lt; 10)", "en": "contested votes (margin &lt; 10)",
                             "de": "umstrittene Abstimmungen (Differenz &lt; 10)", "cs": "sporných hlasování (rozdíl &lt; 10)",
                             "nl": "verdeelde stemmingen (&lt; 10)", "sk": "sporných hlasovaní (&lt; 10)",
                             "fr": "votes serrés (écart &lt; 10)", "da": "tætte afstemninger (&lt; 10)",
                             "hu": "szoros szavazás (&lt; 10)", "uk": "спірних голосувань (&lt; 10)",
                             "lt": "ginčytinų (&lt; 10)", "lv": "strīdīgi (&lt; 10)", "et": "tasavägiseid (&lt; 10)"},
    "stat_sessions_label": {"pl": "sesji w archiwum", "en": "sessions archived", "de": "Sitzungen im Archiv",
                            "cs": "zasedání v archivu", "nl": "vergaderingen", "sk": "zasadnutí",
                            "fr": "séances archivées", "da": "møder i arkivet", "hu": "ülés az archívumban",
                            "uk": "сесій в архіві", "lt": "posėdžių archyve", "lv": "sēdes arhīvā", "et": "istungit arhiivis"},

    # ── Sekcja: wyróżnienia ────────────────────────────────────────────
    "sec_highlights_h2": {"pl": "Wyróżnienia kadencji", "en": "Highlights of the term",
                          "de": "Höhepunkte der Wahlperiode", "cs": "Vyznamenání volebního období",
                          "nl": "Hoogtepunten", "sk": "Highlighty obdobia", "fr": "Faits marquants",
                          "da": "Højdepunkter", "hu": "A ciklus kiemelkedői", "uk": "Головне за каденцію",
                          "lt": "Kadencijos akcentai", "lv": "Sasaukuma akcenti", "et": "Koosseisu tipphetked"},
    "sec_highlights_sub": {"pl": "Najciekawsze nazwiska i decyzje, wprost z rejestru głosowań.",
                           "en": "The most striking names and decisions, straight from the voting record.",
                           "de": "Die auffälligsten Namen und Entscheidungen, direkt aus dem Abstimmungsregister.",
                           "cs": "Nejzajímavější jména a rozhodnutí přímo z registru hlasování."},
    "hl_active_tag": {"pl": "Najaktywniejszy radny", "en": "Most active councillor",
                      "de": "Aktivstes Ratsmitglied", "cs": "Nejaktivnější zastupitel",
                      "nl": "Meest actieve raadslid", "sk": "Najaktívnejší poslanec", "fr": "Élu le plus actif",
                      "da": "Mest aktive medlem", "hu": "Legaktívabb képviselő", "uk": "Найактивніший депутат",
                      "lt": "Aktyviausias narys", "lv": "Aktīvākais deputāts", "et": "Aktiivseim liige"},
    "hl_active_sub": {"pl": "najwyższa aktywność w głosowaniach", "en": "highest voting activity",
                      "de": "höchste Abstimmungsaktivität", "cs": "nejvyšší aktivita v hlasování"},
    "hl_active_unit": {"pl": "aktywności", "en": "activity", "de": "Aktivität", "cs": "aktivity",
                       "nl": "activiteit", "sk": "aktivity", "fr": "activité", "da": "aktivitet",
                       "hu": "aktivitás", "uk": "активність", "lt": "aktyvumo", "lv": "aktivitāte", "et": "aktiivsust"},
    "hl_rebel_tag": {"pl": "Najczęściej głosował przeciw własnemu klubowi", "en": "Most often voted against their own club",
                     "de": "Stimmte am häufigsten gegen die eigene Fraktion", "cs": "Nejčastěji hlasoval proti vlastnímu klubu",
                     "nl": "Stemde het vaakst tegen de eigen fractie", "sk": "Najčastejšie hlasoval proti vlastnému klubu",
                     "fr": "A le plus voté contre son propre groupe", "da": "Stemte oftest mod egen gruppe",
                     "hu": "Legtöbbször a saját frakciója ellen szavazott", "uk": "Найчастіше голосував проти власної фракції",
                     "lt": "Dažniausiai balsavo prieš savo frakciją", "lv": "Visbiežāk balsoja pret savu frakciju",
                     "et": "Hääletas kõige sagedamini oma fraktsiooni vastu"},
    "hl_rebel_sub": {"pl": "rozbieżność z linią klubu", "en": "divergence from the club line",
                     "de": "Abweichung von der Fraktionslinie", "cs": "odchylka od linie klubu"},
    "hl_rebel_unit": {"pl": "razy wbrew", "en": "times against", "de": "mal dagegen", "cs": "krát proti",
                      "nl": "keer tegen", "sk": "krát proti", "fr": "fois contre", "da": "gange imod",
                      "hu": "alkalommal ellen", "uk": "разів проти", "lt": "kartus prieš", "lv": "reizes pret", "et": "korda vastu"},
    "hl_vote_tag": {"pl": "Najbardziej kontrowersyjne głosowanie", "en": "Most contested vote",
                    "de": "Umstrittenste Abstimmung", "cs": "Nejspornější hlasování",
                    "nl": "Meest verdeelde stemming", "sk": "Najspornejšie hlasovanie", "fr": "Vote le plus serré",
                    "da": "Mest omstridte afstemning", "hu": "Legvitatottabb szavazás", "uk": "Найспірніше голосування",
                    "lt": "Ginčytiniausias balsavimas", "lv": "Strīdīgākais balsojums", "et": "Vaieldavaim hääletus"},
    "hl_vote_unit": {"pl": "za : przeciw", "en": "for : against", "de": "dafür : dagegen", "cs": "pro : proti",
                     "nl": "voor : tegen", "sk": "za : proti", "fr": "pour : contre", "da": "for : imod",
                     "hu": "mellette : ellene", "uk": "за : проти", "lt": "už : prieš", "lv": "par : pret", "et": "poolt : vastu"},
    "vote_margin": {"pl": "różnica {n}", "en": "margin {n}", "de": "Differenz {n}", "cs": "rozdíl {n}",
                    "nl": "verschil {n}", "sk": "rozdiel {n}", "fr": "écart {n}", "da": "forskel {n}",
                    "hu": "{n} különbség", "uk": "різниця {n}", "lt": "skirtumas {n}", "lv": "starpība {n}", "et": "vahe {n}"},

    # ── Sekcja: aktywność ──────────────────────────────────────────────
    "sec_activity_h2": {"pl": "Aktywność w czasie", "en": "Activity over time", "de": "Aktivität im Zeitverlauf",
                        "cs": "Aktivita v čase", "nl": "Activiteit in de tijd", "sk": "Aktivita v čase",
                        "fr": "Activité dans le temps", "da": "Aktivitet over tid", "hu": "Aktivitás időben",
                        "uk": "Активність у часі", "lt": "Aktyvumas laikui bėgant", "lv": "Aktivitāte laikā", "et": "Aktiivsus ajas"},
    "sec_activity_sub": {"pl": "Liczba głosowań na sesjach i ile z nich było spornych.",
                         "en": "Number of votes per session and how many were contested.",
                         "de": "Anzahl der Abstimmungen pro Sitzung und wie viele umstritten waren.",
                         "cs": "Počet hlasování na zasedáních a kolik z nich bylo sporných."},
    "legend_votes": {"pl": "głosowania", "en": "votes", "de": "Abstimmungen", "cs": "hlasování",
                     "nl": "stemmingen", "sk": "hlasovania", "fr": "votes", "da": "afstemninger",
                     "hu": "szavazás", "uk": "голосування", "lt": "balsavimai", "lv": "balsojumi", "et": "hääletused"},
    "legend_contested": {"pl": "sporne", "en": "contested", "de": "umstritten", "cs": "sporné",
                         "nl": "verdeeld", "sk": "sporné", "fr": "serrés", "da": "omstridte",
                         "hu": "vitatott", "uk": "спірні", "lt": "ginčytini", "lv": "strīdīgi", "et": "vaieldavad"},

    # ── Sekcja: ostatnie sporne ────────────────────────────────────────
    "sec_contested_h2": {"pl": "Ostatnie sporne głosowania", "en": "Recent contested votes",
                         "de": "Letzte umstrittene Abstimmungen", "cs": "Poslední sporná hlasování",
                         "nl": "Recente verdeelde stemmingen", "sk": "Posledné sporné hlasovania",
                         "fr": "Derniers votes serrés", "da": "Seneste omstridte afstemninger",
                         "hu": "Legutóbbi vitatott szavazások", "uk": "Останні спірні голосування",
                         "lt": "Naujausi ginčytini balsavimai", "lv": "Jaunākie strīdīgie balsojumi", "et": "Viimased vaieldavad hääletused"},
    "sec_contested_sub": {"pl": "Tam, gdzie rada była podzielona, każdy głos ważył najwięcej.",
                          "en": "Where the council was split, every vote mattered most.",
                          "de": "Wo der Rat gespalten war, zählte jede Stimme am meisten.",
                          "cs": "Tam, kde byla rada rozdělená, vážil každý hlas nejvíce."},
    "th_vote": {"pl": "Głosowanie", "en": "Vote", "de": "Abstimmung", "cs": "Hlasování", "nl": "Stemming",
                "sk": "Hlasovanie", "fr": "Vote", "da": "Afstemning", "hu": "Szavazás", "uk": "Голосування",
                "lt": "Balsavimas", "lv": "Balsojums", "et": "Hääletus"},
    "th_date": {"pl": "Data", "en": "Date", "de": "Datum", "cs": "Datum", "nl": "Datum", "sk": "Dátum",
                "fr": "Date", "da": "Dato", "hu": "Dátum", "uk": "Дата", "lt": "Data", "lv": "Datums", "et": "Kuupäev"},
    "th_for": {"pl": "Za", "en": "For", "de": "Dafür", "cs": "Pro", "nl": "Voor", "sk": "Za", "fr": "Pour",
               "da": "For", "hu": "Mellette", "uk": "За", "lt": "Už", "lv": "Par", "et": "Poolt"},
    "th_against": {"pl": "Przeciw", "en": "Against", "de": "Dagegen", "cs": "Proti", "nl": "Tegen", "sk": "Proti",
                   "fr": "Contre", "da": "Imod", "hu": "Ellene", "uk": "Проти", "lt": "Prieš", "lv": "Pret", "et": "Vastu"},
    "th_abstain": {"pl": "Wstrzym.", "en": "Abstain", "de": "Enthalt.", "cs": "Zdržel", "nl": "Onth.",
                   "sk": "Zdržal", "fr": "Abst.", "da": "Hverken", "hu": "Tartózk.", "uk": "Утрим.",
                   "lt": "Susilaikė", "lv": "Atturas", "et": "Erapooletu"},
    "th_split": {"pl": "Rozkład", "en": "Split", "de": "Verteilung", "cs": "Rozložení", "nl": "Verdeling",
                 "sk": "Rozloženie", "fr": "Répartition", "da": "Fordeling", "hu": "Megoszlás", "uk": "Розподіл",
                 "lt": "Pasiskirstymas", "lv": "Sadalījums", "et": "Jaotus"},

    # ── Sekcja: cały serwis ────────────────────────────────────────────
    "sec_all_h2": {"pl": "Cały serwis", "en": "The whole service", "de": "Die ganze Seite",
                   "cs": "Celý web", "nl": "De hele site", "sk": "Celý web", "fr": "Tout le site",
                   "da": "Hele sitet", "hu": "A teljes oldal", "uk": "Увесь сервіс",
                   "lt": "Visa svetainė", "lv": "Visa vietne", "et": "Kogu teenus"},
    "sec_all_sub": {"pl": "Wejdź w dowolną część i sprawdź radnych z każdej strony.",
                    "en": "Enter any part and check councillors from every angle.",
                    "de": "Öffnen Sie einen beliebigen Bereich und prüfen Sie die Ratsmitglieder aus jeder Perspektive.",
                    "cs": "Vstupte do libovolné části a prověřte zastupitele ze všech stran."},
    "nav_label_main": {"pl": "Strony podstawowe", "en": "Core pages", "de": "Hauptseiten", "cs": "Základní stránky",
                       "nl": "Hoofdpagina's", "sk": "Základné stránky", "fr": "Pages principales", "da": "Hovedsider",
                       "hu": "Fő oldalak", "uk": "Основні сторінки", "lt": "Pagrindiniai puslapiai",
                       "lv": "Galvenās lapas", "et": "Põhilehed"},
    "nav_label_extra": {"pl": "Strony dodatkowe", "en": "More pages", "de": "Weitere Seiten", "cs": "Další stránky",
                        "nl": "Meer pagina's", "sk": "Ďalšie stránky", "fr": "Pages supplémentaires", "da": "Flere sider",
                        "hu": "További oldalak", "uk": "Додаткові сторінки", "lt": "Daugiau puslapių",
                        "lv": "Vairāk lapu", "et": "Veel lehti"},
    "nav_councilors_title": {"pl": "Lista radnych", "en": "Councillor list", "de": "Liste der Ratsmitglieder",
                             "cs": "Seznam zastupitelů", "nl": "Lijst raadsleden", "sk": "Zoznam poslancov",
                             "fr": "Liste des élus", "da": "Liste over medlemmer", "hu": "Képviselők listája",
                             "uk": "Список депутатів", "lt": "Narių sąrašas", "lv": "Deputātu saraksts", "et": "Liikmete nimekiri"},
    "nav_councilors_desc": {"pl": "Ranking, frekwencja i karta każdego radnego z pełną historią głosów.",
                            "en": "Ranking, attendance and a card for every councillor with full voting history.",
                            "de": "Ranking, Anwesenheit und ein Profil jedes Ratsmitglieds mit vollständiger Abstimmungshistorie.",
                            "cs": "Žebříček, účast a karta každého zastupitele s celou historií hlasování."},
    "nav_sessions_title": {"pl": "Sesje", "en": "Sessions", "de": "Sitzungen", "cs": "Zasedání", "nl": "Vergaderingen",
                           "sk": "Zasadnutia", "fr": "Séances", "da": "Møder", "hu": "Ülések", "uk": "Сесії",
                           "lt": "Posėdžiai", "lv": "Sēdes", "et": "Istungid"},
    "nav_sessions_desc": {"pl": "Porządek obrad, protokoły i wyniki każdej sesji rady.",
                          "en": "Agenda, minutes and results of every council session.",
                          "de": "Tagesordnung, Protokolle und Ergebnisse jeder Ratssitzung.",
                          "cs": "Program, zápisy a výsledky každého zasedání rady."},
    "nav_votes_title": {"pl": "Głosowania", "en": "Votes", "de": "Abstimmungen", "cs": "Hlasování", "nl": "Stemmingen",
                        "sk": "Hlasovania", "fr": "Votes", "da": "Afstemninger", "hu": "Szavazások", "uk": "Голосування",
                        "lt": "Balsavimai", "lv": "Balsojumi", "et": "Hääletused"},
    "nav_votes_desc": {"pl": "Pełny, imienny rejestr głosowań z rozkładem za, przeciw, wstrzymanie.",
                       "en": "Full recorded-vote register with for / against / abstain breakdown.",
                       "de": "Vollständiges namentliches Abstimmungsregister mit Aufschlüsselung dafür / dagegen / Enthaltung.",
                       "cs": "Úplný jmenovitý registr hlasování s rozdělením pro, proti, zdržel se."},
    "nav_interp_title": {"pl": "Interpelacje", "en": "Interpellations", "de": "Anfragen", "cs": "Interpelace",
                         "nl": "Interpellaties", "sk": "Interpelácie", "fr": "Interpellations", "da": "Forespørgsler",
                         "hu": "Interpellációk", "uk": "Запити", "lt": "Paklausimai", "lv": "Pieprasījumi", "et": "Arupärimised"},
    "nav_interp_desc": {"pl": "Pytania i wnioski radnych wraz z odpowiedziami urzędu.",
                        "en": "Councillors' questions and motions with the administration's replies.",
                        "de": "Fragen und Anträge der Ratsmitglieder mit den Antworten der Verwaltung.",
                        "cs": "Otázky a podněty zastupitelů spolu s odpověďmi úřadu."},
    "nav_budget_title": {"pl": "Budżety", "en": "Budgets", "de": "Haushalte", "cs": "Rozpočty", "nl": "Begrotingen",
                         "sk": "Rozpočty", "fr": "Budgets", "da": "Budgetter", "hu": "Költségvetések", "uk": "Бюджети",
                         "lt": "Biudžetai", "lv": "Budžeti", "et": "Eelarved"},
    "nav_budget_desc": {"pl": "Wydatki miasta i to, kto jak głosował nad pieniędzmi.",
                        "en": "City spending and how each councillor voted on the money.",
                        "de": "Ausgaben der Stadt und wie über das Geld abgestimmt wurde.",
                        "cs": "Výdaje města a jak kdo hlasoval o penězích."},
    "nav_budget_desc_assembly": {"pl": "Wydatki województwa i to, kto jak głosował nad pieniędzmi.",
                                 "en": "Regional spending and how each councillor voted on the money.",
                                 "de": "Ausgaben des Landes und wie über das Geld abgestimmt wurde."},
    "nav_committees_title": {"pl": "Komisje", "en": "Committees", "de": "Ausschüsse", "cs": "Komise", "nl": "Commissies",
                             "sk": "Komisie", "fr": "Commissions", "da": "Udvalg", "hu": "Bizottságok", "uk": "Комісії",
                             "lt": "Komitetai", "lv": "Komitejas", "et": "Komisjonid"},
    "nav_committees_desc": {"pl": "Składy komisji i przebieg prac nad drukami przed sesją.",
                            "en": "Committee memberships and how bills progress before a session.",
                            "de": "Ausschussbesetzungen und der Verlauf der Vorlagen vor einer Sitzung.",
                            "cs": "Složení komisí a průběh práce na tiscích před zasedáním."},

    # ── Wiarygodność ───────────────────────────────────────────────────
    "proof_votes_label": {"pl": "głosowań przeanalizowanych", "en": "votes analysed", "de": "analysierte Abstimmungen",
                          "cs": "analyzovaných hlasování", "nl": "geanalyseerde stemmingen", "sk": "analyzovaných hlasovaní",
                          "fr": "votes analysés", "da": "analyserede afstemninger", "hu": "elemzett szavazás",
                          "uk": "проаналізованих голосувань", "lt": "išanalizuotų balsavimų", "lv": "analizēti balsojumi", "et": "analüüsitud hääletust"},
    "proof_councilors_label": {"pl": "radnych monitorowanych", "en": "councillors monitored", "de": "beobachtete Ratsmitglieder",
                               "cs": "sledovaných zastupitelů", "nl": "gevolgde raadsleden", "sk": "sledovaných poslancov",
                               "fr": "élus suivis", "da": "overvågede medlemmer", "hu": "figyelt képviselő",
                               "uk": "депутатів під наглядом", "lt": "stebimų narių", "lv": "uzraudzīto deputātu", "et": "jälgitavat liiget"},
    "proof_freq_value": {"pl": "2× dziennie", "en": "2× a day", "de": "2× täglich", "cs": "2× denně",
                         "nl": "2× per dag", "sk": "2× denne", "fr": "2× par jour", "da": "2× dagligt",
                         "hu": "napi 2×", "uk": "2× на день", "lt": "2× per dieną", "lv": "2× dienā", "et": "2× päevas"},
    "proof_freq_label": {"pl": "dane aktualizowane", "en": "data refreshed", "de": "Daten aktualisiert",
                         "cs": "data aktualizována", "nl": "data ververst", "sk": "dáta aktualizované",
                         "fr": "données mises à jour", "da": "data opdateret", "hu": "adat frissítve",
                         "uk": "дані оновлюються", "lt": "duomenys atnaujinami", "lv": "dati atjaunoti", "et": "andmed uuendatud"},
    "proof_note": {"pl": "Dane pochodzą bezpośrednio z {bip} i są aktualizowane automatycznie.",
                   "en": "Data comes directly from {bip} and is updated automatically.",
                   "de": "Die Daten stammen direkt aus {bip} und werden automatisch aktualisiert.",
                   "cs": "Data pocházejí přímo z {bip} a aktualizují se automaticky."},

    # ── Final CTA ──────────────────────────────────────────────────────
    "cta_final_h3": {"pl": "Sprawdź swojego radnego.", "en": "Check your councillor.",
                     "de": "Prüfen Sie Ihr Ratsmitglied.", "cs": "Prověřte svého zastupitele.",
                     "nl": "Controleer uw raadslid.", "sk": "Preverte svojho poslanca.",
                     "fr": "Vérifiez votre élu.", "da": "Tjek dit rådsmedlem.", "hu": "Ellenőrizze a képviselőjét.",
                     "uk": "Перевірте свого депутата.", "lt": "Patikrinkite savo narį.",
                     "lv": "Pārbaudiet savu deputātu.", "et": "Kontrolli oma volinikku."},
    "cta_final_p": {"pl": "Pełny rejestr jest otwarty i darmowy. Zobacz, jak głosował radny z Twojego okręgu, i porównaj go z resztą rady.",
                    "en": "The full register is open and free. See how the councillor from your district voted and compare them with the rest of the council.",
                    "de": "Das vollständige Register ist offen und kostenlos. Sehen Sie, wie das Ratsmitglied aus Ihrem Wahlkreis abgestimmt hat, und vergleichen Sie es mit dem übrigen Rat.",
                    "cs": "Úplný registr je otevřený a zdarma. Podívejte se, jak hlasoval zastupitel z vašeho obvodu, a porovnejte ho se zbytkem rady."},
    "cta_final_primary": {"pl": "Sprawdź swojego radnego", "en": "Check your councillor",
                          "de": "Ratsmitglied prüfen", "cs": "Prověřit zastupitele", "nl": "Controleer uw raadslid",
                          "sk": "Preveriť poslanca", "fr": "Vérifier votre élu", "da": "Tjek dit medlem",
                          "hu": "Képviselő ellenőrzése", "uk": "Перевірити депутата", "lt": "Tikrinti narį",
                          "lv": "Pārbaudīt deputātu", "et": "Kontrolli volinikku"},
    "cta_rss": {"pl": "Subskrybuj RSS", "en": "Subscribe to RSS", "de": "RSS abonnieren", "cs": "Odebírat RSS",
                "nl": "Abonneer op RSS", "sk": "Odoberať RSS", "fr": "S'abonner au RSS", "da": "Abonnér på RSS",
                "hu": "RSS feliratkozás", "uk": "Підписатися на RSS", "lt": "Prenumeruoti RSS",
                "lv": "Abonēt RSS", "et": "Telli RSS"},

    # ── Footer ─────────────────────────────────────────────────────────
    "footer_tagline": {"pl": "to niezależny, otwarty monitoring rady", "en": "is an independent, open monitor of the council",
                       "de": "ist ein unabhängiges, offenes Monitoring des Rates", "cs": "je nezávislý, otevřený monitoring rady"},
    "footer_data_from": {"pl": "Dane pochodzą z", "en": "Data comes from", "de": "Daten stammen aus",
                         "cs": "Data pocházejí z"},
    "footer_license": {"pl": "Kod na licencji AGPL", "en": "Code under the AGPL licence",
                       "de": "Code unter der AGPL-Lizenz", "cs": "Kód pod licencí AGPL"},
    "footer_repo": {"pl": "repozytorium", "en": "repository", "de": "Repository", "cs": "repozitář",
                    "nl": "repository", "sk": "repozitár", "fr": "dépôt", "da": "repository", "hu": "tároló",
                    "uk": "репозиторій", "lt": "saugykla", "lv": "repozitorijs", "et": "hoidla"},
    "footer_other_cities": {"pl": "Pozostałe miasta", "en": "Other cities", "de": "Weitere Städte",
                            "cs": "Další města", "nl": "Andere steden", "sk": "Ďalšie mestá", "fr": "Autres villes",
                            "da": "Andre byer", "hu": "Más városok", "uk": "Інші міста", "lt": "Kiti miestai",
                            "lv": "Citas pilsētas", "et": "Teised linnad"},
    "footer_updated_2x": {"pl": "i są odświeżane dwa razy dziennie", "en": "and is refreshed twice a day",
                          "de": "und werden zweimal täglich aktualisiert", "cs": "a aktualizují se dvakrát denně"},
    "back_home": {"pl": "Wróć na stronę główną", "en": "Back to home", "de": "Zurück zur Startseite",
                  "cs": "Zpět na úvod", "nl": "Terug naar home", "sk": "Späť na úvod", "fr": "Retour à l'accueil",
                  "da": "Tilbage til forsiden", "hu": "Vissza a főoldalra", "uk": "На головну",
                  "lt": "Į pradžią", "lv": "Atpakaļ uz sākumu", "et": "Tagasi avalehele"},

    # ── Lista radnych (/councillors/) ──────────────────────────────────
    "crumb_home": {"pl": "Strona główna", "en": "Home", "de": "Startseite", "cs": "Úvod", "nl": "Home",
                   "sk": "Úvod", "fr": "Accueil", "da": "Forside", "hu": "Főoldal", "uk": "Головна",
                   "lt": "Pradžia", "lv": "Sākums", "et": "Avaleht"},
    "crumb_councilors": {"pl": "Radni", "en": "Councillors", "de": "Ratsmitglieder", "cs": "Zastupitelé",
                         "nl": "Raadsleden", "sk": "Poslanci", "fr": "Élus", "da": "Medlemmer", "hu": "Képviselők",
                         "uk": "Депутати", "lt": "Nariai", "lv": "Deputāti", "et": "Liikmed"},
    "councilors_title": {"pl": "Radni {name}", "en": "{name} councillors", "de": "Ratsmitglieder {name}",
                         "cs": "Zastupitelé {name}", "nl": "Raadsleden {name}", "sk": "Poslanci {name}",
                         "fr": "Élus de {name}", "da": "Medlemmer {name}", "hu": "{name} képviselői",
                         "uk": "Депутати {name}", "lt": "{name} nariai", "lv": "{name} deputāti", "et": "{name} volinikud"},
    "councilors_sub": {"pl": "{n} radnych w kadencji. Kliknij nagłówek, żeby posortować.",
                       "en": "{n} councillors this term. Click a header to sort.",
                       "de": "{n} Ratsmitglieder in der Wahlperiode. Klicken Sie auf eine Spalte zum Sortieren.",
                       "cs": "{n} zastupitelů ve volebním období. Klikněte na záhlaví pro řazení."},
    "search_placeholder": {"pl": "Szukaj radnego…", "en": "Search councillor…", "de": "Ratsmitglied suchen…",
                           "cs": "Hledat zastupitele…", "nl": "Zoek raadslid…", "sk": "Hľadať poslanca…",
                           "fr": "Rechercher un élu…", "da": "Søg medlem…", "hu": "Képviselő keresése…",
                           "uk": "Пошук депутата…", "lt": "Ieškoti nario…", "lv": "Meklēt deputātu…", "et": "Otsi volinikku…"},
    "all_clubs": {"pl": "Wszystkie kluby", "en": "All clubs", "de": "Alle Fraktionen", "cs": "Všechny kluby",
                  "nl": "Alle fracties", "sk": "Všetky kluby", "fr": "Tous les groupes", "da": "Alle grupper",
                  "hu": "Összes frakció", "uk": "Усі фракції", "lt": "Visos frakcijos", "lv": "Visas frakcijas", "et": "Kõik fraktsioonid"},
    "th_councilor": {"pl": "Radny", "en": "Councillor", "de": "Ratsmitglied", "cs": "Zastupitel", "nl": "Raadslid",
                     "sk": "Poslanec", "fr": "Élu", "da": "Medlem", "hu": "Képviselő", "uk": "Депутат",
                     "lt": "Narys", "lv": "Deputāts", "et": "Volinik"},
    "th_club": {"pl": "Klub", "en": "Club", "de": "Fraktion", "cs": "Klub", "nl": "Fractie", "sk": "Klub",
                "fr": "Groupe", "da": "Gruppe", "hu": "Frakció", "uk": "Фракція", "lt": "Frakcija", "lv": "Frakcija", "et": "Fraktsioon"},
    "th_attendance": {"pl": "Frekwencja", "en": "Attendance", "de": "Anwesenheit", "cs": "Účast", "nl": "Aanwezigheid",
                      "sk": "Účasť", "fr": "Présence", "da": "Fremmøde", "hu": "Részvétel", "uk": "Відвідуваність",
                      "lt": "Lankomumas", "lv": "Apmeklējums", "et": "Osavõtt"},
    "th_votes_count": {"pl": "Głosów", "en": "Votes", "de": "Stimmen", "cs": "Hlasů", "nl": "Stemmen",
                       "sk": "Hlasov", "fr": "Votes", "da": "Stemmer", "hu": "Szavazat", "uk": "Голосів",
                       "lt": "Balsų", "lv": "Balsu", "et": "Hääli"},
    "th_agreement": {"pl": "Zgodność z klubem", "en": "Club agreement", "de": "Fraktionstreue",
                     "cs": "Shoda s klubem", "nl": "Fractiediscipline", "sk": "Zhoda s klubom",
                     "fr": "Accord avec le groupe", "da": "Gruppeloyalitet", "hu": "Frakcióhűség",
                     "uk": "Збіг із фракцією", "lt": "Sutapimas su frakcija", "lv": "Saskaņa ar frakciju", "et": "Kooskõla fraktsiooniga"},
    "shown_count": {"pl": "Pokazano {n} z {total}", "en": "Showing {n} of {total}", "de": "{n} von {total} angezeigt",
                    "cs": "Zobrazeno {n} z {total}", "nl": "{n} van {total} getoond", "sk": "Zobrazené {n} z {total}",
                    "fr": "{n} sur {total} affichés", "da": "Viser {n} af {total}", "hu": "{n} / {total} megjelenítve",
                    "uk": "Показано {n} з {total}", "lt": "Rodoma {n} iš {total}", "lv": "Rāda {n} no {total}", "et": "Kuvatud {n} / {total}"},
}


def catalog(locale: str, assembly: bool = False) -> dict[str, str]:
    """Zwróć słownik key -> tekst dla locale, fallback locale -> en -> pl.

    assembly=True: po zbudowaniu katalogu bazowego nakłada warianty
    `<key>_assembly` (sejmik PL / Landtag DE) na klucz bazowy `<key>`.
    Dzięki temu renderLandingHTML/build_seo_content czytają te same klucze
    (hero_title, hero_eyebrow, insight_full, nav_budget_desc), a treść jest
    poprawna dla assembly bez gałęzi w rendererze.
    """
    loc = (locale or "pl").lower()
    out = {}
    for key, variants in STRINGS.items():
        if key.endswith("_assembly"):
            continue
        out[key] = variants.get(loc) or variants.get("en") or variants.get("pl") or key
    if assembly:
        for base_key in list(out.keys()):
            variants = STRINGS.get(base_key + "_assembly")
            if variants:
                out[base_key] = (variants.get(loc) or variants.get("en")
                                 or variants.get("pl") or out[base_key])
    return out
